### ISSUE TITLE
bug: `WordPart::AnyWildcard` is not a valid part for unbound string ends

### ISSUE THREAD

**Issue by kyranet** [skyra-project/word-match#6]
Currently, only `WordPart::SingleWildcard` is considered, but it would be nice for `WordPart::AnyWildcard` to be as well.

https://github.com/skyra-project/word-match/blob/8ceb4f23beb7b5d604027a9a60a0f8fb900e3687/src/word.rs#L121-L129

**Comment by Nytelife26** [comment]
aren't the current tests inconsistent with your documentation?

according to the documentation, `*` should match a single character or repeated single character (`abt` or `acct`) but not mixed characters (`acbt`). however, the test identifies `*bar` as matching `rebar`, which violates the latter rule. to maintain consistency with your stated rules, should the library not require `**bar` to match something like `rebar`, with `*bar` only matching instances like `abar` or `eebar`?

**Comment by kyranet** [comment]
It was `*bar` to match `rebar` because compatibility with current Skyra, but we can change that and migrate when we switch so the current behaviour is unchanged on Skyra's side.

**Comment by Nytelife26** [comment]
so, to confirm, i should work on making the functionality line up as i said, and mapping will be done on Skyra's end so it behaves the same for end-users?

**Comment by kyranet** [comment]
If the behaviour is changed for the better, which is true in this case, yes
